# Generated by Django 3.0.3 on 2020-09-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cname',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='mname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
