# Generated by Django 3.0.3 on 2020-09-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200923_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cpasswords',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='manager',
            name='mpasswords',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
