# Generated by Django 3.0.3 on 2020-09-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200923_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clevel',
            field=models.BooleanField(default=False),
        ),
    ]
