# Generated by Django 3.0.3 on 2020-09-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_client_clevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cemail',
            field=models.EmailField(max_length=254),
        ),
    ]
