# Generated by Django 3.0.3 on 2020-10-02 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200924_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='mage',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='memail',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='mgender',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='mphonenum',
        ),
    ]
