# Generated by Django 3.0.3 on 2020-10-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20201002_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='clevel',
        ),
    ]
