# Generated by Django 3.0.3 on 2020-09-24 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='whouse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='information.Warehouse'),
        ),
    ]
