# Generated by Django 3.0.3 on 2020-09-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20200925_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='hcategory',
            field=models.CharField(choices=[('货物存储', '货物存储'), ('娱乐场所', '娱乐场所'), ('', '')], default=False, max_length=4),
        ),
    ]
