# Generated by Django 3.0.3 on 2020-09-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_auto_20200925_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='wprice',
            field=models.FloatField(default=0),
        ),
    ]
