# Generated by Django 3.0.3 on 2020-09-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_auto_20200925_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='wphoto',
            field=models.ImageField(blank=True, default='', null=True, upload_to='../../static/images'),
        ),
        migrations.AddField(
            model_name='ware',
            name='wsalenum',
            field=models.IntegerField(default=0),
        ),
    ]
