# Generated by Django 3.0.3 on 2020-09-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0012_auto_20200927_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='wname',
            field=models.CharField(max_length=50),
        ),
    ]
