# Generated by Django 3.0.3 on 2020-09-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0013_auto_20200927_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='hphoto',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
