# Generated by Django 3.0.3 on 2020-09-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0015_warehouse_hprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='wdescription',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
