# Generated by Django 3.0.3 on 2020-09-29 15:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200924_2110'),
        ('information', '0016_ware_wdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WOnum', models.IntegerField(default=1)),
                ('WOdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('WOaddress', models.CharField(max_length=100)),
                ('WOclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client')),
                ('WOware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Ware')),
            ],
        ),
    ]
