# Generated by Django 3.0.3 on 2020-09-29 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200924_2110'),
        ('information', '0017_wareorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wareorder',
            name='WOaddress',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='HouseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOfromdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('HOduration', models.IntegerField()),
                ('HOclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client')),
                ('HOhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Warehouse')),
            ],
        ),
    ]
