# Generated by Django 3.0.3 on 2020-09-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0018_auto_20200930_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseorder',
            name='HOhouse',
            field=models.ForeignKey(limit_choices_to={'hisoccupied': False}, on_delete=django.db.models.deletion.CASCADE, to='information.Warehouse'),
        ),
    ]
