# Generated by Django 3.0.3 on 2020-10-01 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0019_auto_20200930_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitorflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vdate', models.DateTimeField()),
                ('Vnum', models.IntegerField(default=0)),
                ('Vhouse', models.ForeignKey(limit_choices_to={'hcategory': '娱乐场所'}, on_delete=django.db.models.deletion.CASCADE, to='information.Warehouse')),
            ],
        ),
    ]
