# Generated by Django 3.0.3 on 2020-10-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0021_auto_20201001_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Warehouse')),
                ('wares', models.ManyToManyField(to='information.Ware')),
            ],
        ),
    ]
