# Generated by Django 3.0.3 on 2020-10-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0022_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='wares',
        ),
        migrations.AddField(
            model_name='test',
            name='wares',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='information.Ware'),
        ),
    ]
