# Generated by Django 3.0.3 on 2020-10-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0023_auto_20201001_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='house',
            field=models.ForeignKey(limit_choices_to={'hcategory': '货物存储'}, on_delete=django.db.models.deletion.CASCADE, to='information.Warehouse'),
        ),
    ]
