# Generated by Django 3.0.3 on 2020-10-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0024_auto_20201001_2232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='HouseWare',
        ),
    ]
