# Generated by Django 3.0.3 on 2020-10-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0025_auto_20201001_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ware',
            name='whouse',
        ),
    ]
