# Generated by Django 3.0.3 on 2020-10-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200924_2110'),
        ('information', '0026_remove_ware_whouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(limit_choices_to={'hcategory': ['货物存储', '娱乐场所']}, on_delete=django.db.models.deletion.CASCADE, to='information.Warehouse')),
                ('manager', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='login.Manager')),
            ],
        ),
    ]
