# Generated by Django 3.0.3 on 2020-10-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200924_2110'),
        ('information', '0027_managerhouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerhouse',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Warehouse', unique=True),
        ),
        migrations.AlterField(
            model_name='managerhouse',
            name='manager',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='login.Manager', unique=True),
        ),
    ]
