# Generated by Django 3.0.3 on 2020-10-01 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0028_auto_20201001_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseorder',
            name='HOhouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Warehouse'),
        ),
    ]
