# Generated by Django 3.0.3 on 2020-10-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0030_auto_20201002_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ware',
            name='wmeasureunit',
        ),
    ]
